[package]
name = "peertube-ser"
version = "0.1.0"
authors = ["SosthÃ¨ne GuÃ©don <dev@peertube-viewer.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
time = {version = "0.3", features = ["serde"]}

[dev-dependencies]
serde_json = "1"
